bookstore/books/urls.py
from django import urls
from django.urls import path
from . import views

from .views import BookListView, BookDetailView, BookCheckoutView, HomePageView, SearchResultView, ContactPageView, \
    AboutPageView, MyProfileView,SiteReviewView, SiteReviewCreate, SiteReviewDelete, \
    SiteReviewUpdate,MyProfileCreate,MyProfileUpdate


urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('book_list',BookListView.as_view(), name='list'),
    path('details/<int:pk>/',BookDetailView.as_view(), name='details'),
    path('checkout/<int:pk>/',BookCheckoutView.as_view(), name='checkout'),
    path('complete/',views.paymentComplete, name='complete'),

    path('search/', SearchResultView.as_view(), name='search'),
    path('contact/', ContactPageView.as_view(), name='contact'),
    path('about/', AboutPageView.as_view(), name='about'),


    path('myprofile/', MyProfileView.as_view(), name='myprofile'),
    path('createprofile/', MyProfileCreate.as_view(), name='createprofile'),
    path('editprofile/', MyProfileUpdate.as_view(), name='editprofile'),

    path('cart/add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/remove/<int:cart_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('cart/', views.cart, name='cart'),

    path('reviews/', SiteReviewView.as_view(), name='reviews'),
    path('reviewcreate/', SiteReviewCreate.as_view(), name='reviewcreate'),
    path('reviewdelete/<int:pk>/', SiteReviewDelete.as_view(), name='reviewdelete'),
    path('reviewupdate/<int:pk>/', SiteReviewUpdate.as_view(), name='reviewupdate')

]

bookstore/bookstore/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("books.urls")),
    path('',include("accounts.urls")),
    path('account/',include("django.contrib.auth.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookstore/books/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class Book(models.Model):
    title = models.CharField(max_length=150)
    author = models.CharField(max_length=150)
    description = models.CharField(max_length=500)
    price = models.FloatField(null=True,blank=True)
    image_url = models.CharField(max_length=2083,blank=True)
    follow_author = models.CharField(max_length=2083, blank=True)
    book_available = models.BooleanField()

    def __str__(self):
        return self.title

class Order(models.Model):
    product = models.ForeignKey(Book,max_length=200,null=True,blank=True,on_delete=models.SET_NULL)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product.title

class MyProfile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=20)
    email = models.EmailField(max_length=100)
    bio = models.CharField(max_length=200)
    Favorites = models.ManyToManyField(Book)
    address = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name

class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Book, on_delete=models.CASCADE)
    image_url = models.CharField(max_length = 2083, default=False)
    quantity = models.PositiveIntegerField(default=1)
    price = models.DecimalField(max_digits=6, decimal_places=2)

class SiteReview(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.ForeignKey(MyProfile, on_delete=models.CASCADE, null=True, blank=True)
    review = models.CharField(max_length=255, null=True, blank=True)
    rating = models.IntegerField(choices=((1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')), null=True, blank=True)

    def __str__(self):
        return self.review

bookstore/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>bookstore</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <style>
        body {
            background: #ffffff;
        }
        .container-fluid {
            padding: 100px;
            padding-top: 50px;
        }
        .navbar {
            padding: 20px;
            background: #00458a;
            background-image:url("https://png.pngtree.com/back_origin_pic/03/88/19/883f1b0ddd7c6f341e3357fd964b2bfa.jpg")
        }
        .navbar-brand {
            font-weight: bold;
            font-size: 1.5rem;
            color: #f2f2f2;
            text-decoration: none;
        }
        .navbar-brand:hover {
            background-color: transparent;
            color: #f2f2f2;
        }
        .navbar-brand img {
            margin-right: 0.5rem;
            border-radius: 50px;
        }







        .header-link {
            margin: 0 10px;
            padding: 5px;
            border: 0px;
            border-radius: 5px;
            text-decoration: none;
            color: #f2f2f2;
            font-size: 12px;
            transition: background-color 0.3s ease;
        }


        .site-footer {
            background-color: #f8f8f8;
            padding: 20px 0;
            text-align: center;
        }
        .site-footer p {
            margin: 0;
            font-size: 14px;
            color: #666;
        }



#books{
 font-size: 20px;
            color: #660000;
}
.about{
text-align: center;
 color: #660000;
}

    </style>
</head>
<body>
    <nav class="navbar">
        <p class="navbar-brand">
            ഇതൾ
        </p>
       <div class="ml-auto" style="margin-left: auto;">
            <a class="header-link" href="{% url 'list' %}">Home</a>
            <a class="header-link" href="{% url 'contact' %}">Contact</a>
            <a class="header-link" href="{% url 'about' %}">About</a>
        </div>
        <div class="dropdown">
            <button type="button" class="btn dropdown" data-bs-toggle="dropdown">{{ user }}</button>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'myprofile' %}">My profile</a></li>
                  <li><a class="dropdown-item" href="{% url 'list' %}">Books</a></li>
                 <li><a class="dropdown-item" href="{% url 'reviews' %}">Reviews</a></li>
                <li><a class="dropdown-item" href="{% url 'cart' %}">My cart</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
            </ul>
        </div>
<form class="search" action="{% url 'search' %}" method="get">

         <input name="q" class="fas fa-search" type="text"  autocomplete="on"
                placeholder="click to search">
     </form>
    </nav>


<div class="container-details" id="img-container"style="padding:120px;padding-bottom:200px;">
    <div class="row">
    <div class="col-md-6"style="text-align:justify;padding-top:60px;">
 <h3>ABOUT</h3>
        <p>A growing body of research indicates that reading literally changes your mind.</p>
        <P>Reading books benefits both your physical and mental health, and those benefits can last a lifetime. They begin in early childhood and continue through the senior years. Here’s a brief explanation of how reading books can change your brain — and your body — for the better</P>
        </div>
        <div class="col-md-6" style="justify-content:center;">
<img src="https://cdn.dribbble.com/users/2367833/screenshots/7816190/books-_-tv.gif" height="300" width="300">
</div>
 </div>

<footer>
<div class="footer">
    <center>
        <br><h5>Follow us</h5>
        <div class="footer-social">
            <a href="https://www.facebook.com/"><img src="https://cdn-icons-png.flaticon.com/512/2504/2504903.png"
                                                     width="30" height="30"></a>
            <a href="https://www.instagram.com/"><img
                    src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Instagram-Icon.png/1025px-Instagram-Icon.png"
                    width="30" height="30"></a>
            <a href="https://in.linkedin.com/"><img
                    src="https://tse1.mm.bing.net/th?id=OIP.waOtRAV99hCXTCS_RvbK6QHaGp&pid=Api&P=0" width="30"
                    height="30"></a>
        </div>

</div>




    <center>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; 2023  ഇതൾ</p>

                </div>
            </div>
        </div>

    </center>
</footer>

</body>
</html>

bookstore/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
     <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
   <style>
        body {
            background: #f2f2f2;
        }
        .container-fluid {
            padding: 100px;
            padding-top: 50px;
        }
        .navbar {
            padding: 20px;
            background: #00458a;
            background-image:url("https://png.pngtree.com/back_origin_pic/03/88/19/883f1b0ddd7c6f341e3357fd964b2bfa.jpg")
        }
        .navbar-brand {
            font-weight: bold;
            font-size: 1.5rem;
            color: #f2f2f2;
            text-decoration: none;
        }
        .navbar-brand:hover {
            background-color: transparent;
            color: #f2f2f2;
        }
        .navbar-brand img {
            margin-right: 0.5rem;
            border-radius: 50px;
        }
        .site-footer {
            background-color: #f8f8f8;
            padding: 20px 0;
            text-align: center;
        }
        .site-footer p {
            margin: 0;
            font-size: 14px;
            color: #666;
        }
    </style>
</head>
<body>
<nav class="navbar">
        <p class="navbar-brand">
            ഇതൾ
        </p>
       <div class="ml-auto" style="margin-left: auto;">
            <a class="header-link" href="{% url 'home' %}">Home</a>
            <a class="header-link" href="{% url 'contact' %}">Contact</a>
            <a class="header-link" href="{% url 'about' %}">About</a>
        </div>
        <div class="dropdown">
            <button type="button" class="btn dropdown" data-bs-toggle="dropdown">{{ user }}</button>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'myprofile' %}">My profile</a></li>
                <li><a class="dropdown-item" href="{% url 'list' %}">Books</a></li>
                <li><a class="dropdown-item" href="{% url 'reviews' %}">Reviews</a></li>
                <li><a class="dropdown-item" href="{% url 'cart' %}">My cart</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
            </ul>
        </div>
 <form class="search" action="{% url 'search' %}" method="get">

         <input name="q" class="fas fa-search" type="text"  autocomplete="on"
                placeholder="click to search">
     </form>
    </nav>







</body>

{% block content %}

{% endblock content %}
</html>

bookstore/templates/cart.html
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
<style>
.container-fluid {
            min-height: 100%;
            position: relative;
            padding: 100px;
            padding-top: 50px;
            align: center;
        }

        .site-footer {
            background-color: #f8f8f8;
            padding: 20px 0;
            text-align: center;
            bottom: 0;
            width: 100%;
        }
        .site-footer p {
            margin: 0;
            font-size: 14px;
            color: #666;
        }

  </style>

<body style=background:white;>
  <section class="vh-100">
   <div class="container-fluid">
        <div class="title" style="text-align: center; justify-content: center; margin-bottom: 20px; display: flex;">
            <h2 style="margin-right: 20px;">My Cart</h2><img src="https://tse2.mm.bing.net/th?id=OIP.xDJfgu0FjiKi18eFKbgWngHaHa&pid=Api&P=0" height="40px" width="40px">
        </div>
          {% for cart_item in cart_items %}
          <div class="card mb-4">
            <div class="card-body p-4">
  
              <div class="row align-items-center">
                <div class="col-md-2">
                  <img src="{{cart_item.image_url}}"
                    class="img-fluid" alt="Generic placeholder image">
                </div>
                <div class="col-md-2 d-flex justify-content-center">
                  <div>
                    <p class="small text-muted mb-4 pb-2">Name</p>
                    <p class="lead fw-normal mb-0">{{ cart_item.product }}</p>
                  </div>
                </div>
                <div class="col-md-2 d-flex justify-content-center">
                </div>
                <div class="col-md-2 d-flex justify-content-center">
                  <div>
                    <p class="small text-muted mb-4 pb-2">Quantity</p>
                    <p class="lead fw-normal mb-0">{{ cart_item.quantity }}</p>
                  </div>
                </div>
                <div class="col-md-2 d-flex justify-content-center">
                  <div>
                    <p class="small text-muted mb-4 pb-2">Price</p>
                    <p class="lead fw-normal mb-0">{{ cart_item.price}}</p>
                  </div>
                </div>
                <div class="col-md-2 d-flex justify-content-center">
                   <div class="col-sm-1 col-sm-1 d-flex align-items-center justify-content-center">
                        <a class="btn btn-outline-danger" style="font-size: 16px; margin-right: 20px;" href="{% url 'remove_from_cart' cart_item.id %}"><i class="bi bi-trash3"></i></a>
                    </div>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
          <div class="card mb-5">
            <div class="card-body p-4">
  
              <div class="float-end">
                <p class="mb-0 me-5 d-flex align-items-center">
                  <span class="small text-muted me-2">Order total:</span> <span
                    class="lead fw-normal">{{ total }}</span>
                </p>
              </div>
            </div>
          </div>
        
          <div class="d-flex justify-content-end">
            {% if total == 0 %}
            <a href="{% url 'list' %}"><button type="button" class="btn btn-light btn-lg ">Continue shopping</button></a>
            {% else %}
            <a href="{% 'checkout' object.pk % }"><button type="button" class="btn btn-primary btn-lg">Bynow</button></a>
            <a href="{% url 'list' %}"><button type="button" class="btn btn-light btn-lg ">Continue shopping</button></a>
            {% endif %}
            
          </div>
  
        </div>
      </div>
    </div>
  </section>
<footer class="site-footer">
        <div class="container">
            <p>Copyright &copy; 2023  ഇതൾ</p>
        </div>
    </footer>
</body>
</html>

bookstore/templates/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>bookstore</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <style>
        body {
            background: #f2f2f2;
        }
        .container-fluid {
            padding: 100px;
            padding-top: 50px;
        }
        .navbar {
            padding: 20px;
            background: #00458a;
            background-image:url("https://png.pngtree.com/back_origin_pic/03/88/19/883f1b0ddd7c6f341e3357fd964b2bfa.jpg")
        }
        .navbar-brand {
            font-weight: bold;
            font-size: 1.5rem;
            color: #f2f2f2;
            text-decoration: none;
        }
        .navbar-brand:hover {
            background-color: transparent;
            color: #f2f2f2;
        }
        .navbar-brand img {
            margin-right: 0.5rem;
            border-radius: 50px;
        }

        .header-link {
            margin: 0 10px;
            padding: 5px;
            border: 0px;
            border-radius: 5px;
            text-decoration: none;
            color: #f2f2f2;
            font-size: 12px;
            transition: background-color 0.3s ease;
        }
        .header-link:hover {
            background-color: #f2f2f2;
            color: #000;
            text-decoration: None;
        }

        .site-footer {
            background-color: #f8f8f8;
            padding: 20px 0;
            text-align: center;
        }
        .site-footer p {
            margin: 0;
            font-size: 14px;
            color: #666;
        }
    body {
  font-family: Arial, sans-serif;

}

#contact-us{
opacity:.6;
}
  </style>
</head>
<body>
    <nav class="navbar">
        <p class="navbar-brand">
            ഇതൾ
        </p>
       <div class="ml-auto" style="margin-left: auto;">
            <a class="header-link" href="{% url 'list' %}">Home</a>
            <a class="header-link" href="{% url 'contact' %}">Contact</a>
            <a class="header-link" href="{% url 'about' %}">About</a>
        </div>
        <div class="dropdown">
            <button type="button" class="btn dropdown" data-bs-toggle="dropdown">{{ user }}</button>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'myprofile' %}">My profile</a></li>
                  <li><a class="dropdown-item" href="{% url 'list' %}">Books</a></li>
                 <li><a class="dropdown-item" href="{% url 'reviews' %}">Reviews</a></li>
                <li><a class="dropdown-item" href="{% url 'cart' %}">My cart</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
            </ul>
        </div>
<form class="search" action="{% url 'search' %}" method="get">

         <input name="q" class="fas fa-search" type="text"  autocomplete="on"
                placeholder="click to search">
     </form>
    </nav>


<section>
    <div class="container py-5" id="contact-us">
        <div class="card">
            <div class="card-body">
                <h1 class="font-weight-light text-center py-3">Contact Us</h1>
                <div class="row">
                    <div class="col-lg-6 col-md-12 col-sm-12">

                        <div class="row pt-3">
                            <div class="col-lg-1 offset-1 col-md-2 col-sm-2">
                                <span style="font-size: 30px; color: cadetblue"><i
                                        class="fas fa-map-marker-alt"></i></span>
                            </div>

                            <div class="col-lg-10 col-md-9 col-sm-9">
                                <h3 class="font-weight-light">Find Us at the office</h3>
                                <p> ഇതൾ<br>
                                    KOCHI<br>
                                    KERALA
                                </p>
                            </div>
                        </div>

                        <div class="row pt-3">
                            <div class="col-lg-1 offset-1 col-md-2 col-sm-2">
                                <span style="font-size: 30px; color: coral"><i class="fas fa-phone-volume"></i></span>
                            </div>

                            <div class="col-lg-10 col-md-9 col-sm-9">
                                <h3 class="font-weight-light">Give Us a Ring</h3>
                                <p>Amritha pattali<br>
                                    +91 0000000000<br>
                                    kochi
                                </p>
                            </div>
                        </div>

                    </div>


                </div>
            </div>

        </div>
    </div>
    </div>
</section>

<footer>
    <center>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; 2023  ഇതൾ</p>

                </div>
            </div>
        </div>
</footer>
</center>
</body>
</html>

bookstore/templates/create-review.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>reads.com</title>
    <meta charset="UTF-8">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <style>
        body {
            background: white;
            height: 100%;
            margin: 0;
        }
        .container-fluid {
            min-height: 100%;
            position: relative;
            padding: 100px;
            padding-top: 50px;
            align: center;
        }
        .navbar {
            padding: 20px;
             background-image:url("https://png.pngtree.com/back_origin_pic/03/88/19/883f1b0ddd7c6f341e3357fd964b2bfa.jpg")

        }
        .navbar-brand {
            font-weight: bold;
            font-size: 1.5rem;
            color: #f2f2f2;
            text-decoration: none;
        }
        .navbar-brand:hover {
            background-color: transparent;
            color: #f2f2f2;
        }
        .header-link {
            margin: 0 10px;
            padding: 5px;
            border: 0px;
            border-radius: 5px;
            text-decoration: none;
            color: #f2f2f2;
            font-size: 12px;
            transition: background-color 0.3s ease;
        }
        .header-link:hover {
            background-color: #f2f2f2;
            color: #000;
            text-decoration: None;
        }
        .card {
            padding: 30px;
            border: none;
            box-shadow: 0 2px 6px rgba(0,0,0,0.4);
        }
        .form-group {
            margin-bottom: 20px;
        }
        .site-footer {
            background-color: #f8f8f8;
            padding: 20px 0;
            text-align: center;
            bottom: 0;
            width: 100%;
        }
        .site-footer p {
            margin: 0;
            font-size: 14px;
            color: #666;
        }
    </style>
</head>
<body>
    <nav class="navbar">
        <p class="navbar-brand">
            ഇതൾ
        </p>
       <div class="ml-auto" style="margin-left: auto;">
            <a class="header-link" href="{% url 'home' %}">Home</a>
            <a class="header-link" href="{% url 'contact' %}">Contact</a>
            <a class="header-link" href="{% url 'about' %}">About</a>
        </div>

<form class="search" action="{% url 'search' %}" method="get">

         <input name="q" class="fas fa-search" type="text"  autocomplete="on"
                placeholder="click to search">
     </form>
    </nav>
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-6">
                <h4 style="margin-bottom: 40px;">Rate our site</h4>
                <div class="card">
                    <form method="post">
                    {% csrf_token %}
                        <div class="form-group">
                            <label for="id_review" style="font-weight: bold; margin-bottom: 10px;">Review:</label>
                            <textarea class="form-control" id="id_review" name="review" rows="3">{{ object.review }}</textarea>
                        </div>
                        <div class="form-group">
                            <label for="id_rating" style="font-weight: bold; margin-bottom: 10px;">Rating:</label>
                            <select class="form-control" id="id_rating" name="rating">
                                <option value="1" {% if object.rating == 1 %}selected{% endif %}>1 star</option>
                                <option value="2" {% if object.rating == 2 %}selected{% endif %}>2 stars</option>
                                <option value="3" {% if object.rating == 3 %}selected{% endif %}>3 stars</option>
                                <option value="4" {% if object.rating == 4 %}selected{% endif %}>4 stars</option>
                                <option value="5" {% if object.rating == 5 %}selected{% endif %}>5 stars</option>
                            </select>
                        </div>
                        <button type="submit" class="btn btn-outline-danger" style="font-size: 12px;">Save</button>
                    </form>
                </div>
            </div>

        </div>
    </div>
    <footer class="site-footer">
        <div class="container">
            <p>Copyright &copy; 2023  ഇതൾ</p>
        </div>
    </footer>
</body>
</html>

bookstore/templates/search.html
{% extends 'base.html' %}
{% block title %} search {% endblock title %}
{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SEARCH</title>
    <style>

    </style>
</head>
<body>
<center>
<h3 class="text-secondary">Search results</h3>
{% for every in object_list %}
<div>

    <h3><a href="{% url 'details' every.pk %}">{{ every.title}}</a></h3>
    <p author:{{ every.author}}</p>

</div>
{% empty %}
<h5>nothing found</h5>
 {% endfor %}
    </center>
</body>
</html>
{% endblock content %}